spring:
  datasource:
    url: jdbc:mysql://uoft5vubkty0xptn:hpjmHlMUe5Z0i4NKossn@bnhonjpurtzzrycg06jl-mysql.services.clever-cloud.com:3306/bnhonjpurtzzrycg06jl
    username: uoft5vubkty0xptn
    password: hpjmHlMUe5Z0i4NKossn
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect